### ISSUE TITLE
print player record with average

### ISSUE THREAD

**Issue by 23bca300** [vtcbca/internal-exam-23bca300#2]
In question no. 8 what it does mean player record with average

**Comment by amitvtcbb** [comment]
YOU HAVE TO READ CSV FILE USING READER OBJECT . TAKE MATCH AND RUN FIELD AND STORE IN SOME VARIABLE. AFTER THEN CALCULATE AVERAGE.

**Comment by 23bca300** [comment]
> YOU HAVE TO READ CSV FILE USING READER OBJECT . TAKE MATCH AND RUN FIELD AND STORE IN SOME VARIABLE. AFTER THEN CALCULATE AVERAGE.

SIR CAN YOU EXPLAIN ME HOW TO EXPORT A FILE INTO CSV IN PYTHON.
CAN YOU GIVE ME A SYNTAX?
