### ISSUE TITLE
I SOLVED THIS PROGRAM!!

### ISSUE THREAD

**Issue by 23bca300** [vtcbca/internal-exam-23bca300#3]
But if you think any changes is needed or some other methods ...Then please explain!

**Comment by 23bca274** [comment]
> But if you think any changes is needed or some other methods ...Then please explain!


You did well but if you want more efficient result of your program you've to first write records in CSV file [w.writerows] and then read records in CSV file and then print it .

It will print your records which is visible on python jupyter notebook. 

Hope this may help you. 

@23bca300
